import type { NextPage } from "next";
import Head from "next/head";
import { Chat, Code, Eye, EyeSlash, MagnifyingGlass, SquaresFour, TreeStructure } from "phosphor-react";
import { useState } from "react";

const Home: NextPage = () => {
  const [visible, setVisible] = useState(false);
  return (
    <div className="flex h-screen w-screen flex-col items-center justify-center bg-slate-200">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex  min-h-screen w-full flex-col md:flex-row-reverse">

        <div className="flex flex-col py-4 bg-blue-600 md:h-screen md:w-1/3 md:px-20">
          <div className="h-screen items-center justify-center flex flex-col px-12 py-4  md:px-28">
            <h3 className=" text-2xl font-semibold text-white md:mb-12">
              Dummy Heading
            </h3>
            <p className="text-xs font-light leading-6 text-white">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati
              modi ex quam qui dolor sit amet consectetur adipisicing ea error
              corrupti laudantium ipsa rem dolor sit adipisicing?
            </p>
          </div>
          <div className="flex justify-end gap-2 mr-4">
            <div className="bg-gray-300 rounded-full w-8 h-8 md:w-10 md:h-10 flex justify-center items-center text-gray-500">
              <Chat size={20}/>
            </div>
            <div className="bg-gray-300 rounded-full w-8 h-8 md:w-10 md:h-10 flex justify-center items-center text-gray-500">
              <MagnifyingGlass size={20}/>
            </div>
            <div className="bg-gray-300 rounded-full w-8 h-8 md:w-10 md:h-10 flex justify-center items-center text-gray-500">
              <Code size={20}/>
            </div>
            <div className="bg-gray-300 rounded-full w-8 h-8 md:w-10 md:h-10 flex justify-center items-center text-gray-500">
              <TreeStructure size={20}/>
            </div>
            <div className="bg-gray-300 rounded-full w-8 h-8 md:w-10 md:h-10 flex justify-center items-center text-gray-500">
              <SquaresFour size={20}/>
            </div>
            
          </div>
        </div>

        <div className="flex flex-col bg-white p-2 md:w-2/3">
          <p className="w-full text-right text-[10px] font-bold tracking-wide">
            Step 1 of 3 ...
          </p>
          <div className="mt-10 flex h-[calc(100vh-50px)] items-center justify-center">
            <div className="flex w-full flex-col items-start justify-center gap-4 p-2 md:w-[385px]">
              <h3 className="mb-4 text-xl font-semibold">
                Lets set up your account
              </h3>
              <div className="mb-4 flex items-center gap-2">
                <p className="text-[10px]">Already have an account?</p>
                <button className="text-[10px] font-bold text-blue-600">
                  Sign in
                </button>
              </div>
              <form className="flex w-full flex-col gap-3">
                <input
                  type="text"
                  placeholder="Your name"
                  className="w-full rounded-md border border-gray-100 p-2 placeholder:text-[10px]"
                />
                <input
                  type="email"
                  placeholder="Email address"
                  className="w-full rounded-md border border-gray-100 p-2 placeholder:text-[10px]"
                />
                <select className="w-full rounded-md border border-gray-100 p-2 text-[10px] text-gray-500">
                  <option selected>I would describe my user type as ...</option>
                </select>
                <div className="relative">
                  <input
                    type={visible ? "text" : "password"}
                    placeholder="Password"
                    className="w-full rounded-md border border-gray-100 p-2 placeholder:text-[10px]"
                  />
                  <div onClick={() => setVisible(!visible)}>
                    {visible ? (
                      <EyeSlash
                        size={16}
                        color="#706f70"
                        weight="light"
                        className=" absolute top-4 right-4"
                      />
                    ) : (
                      <Eye
                        size={16}
                        color="#706f70"
                        weight="light"
                        className=" absolute top-4 right-4"
                      />
                    )}
                  </div>
                  <span className="text-[8px] text-gray-400">
                    Minimum 8 characters
                  </span>
                </div>
                <button className="rounded-md bg-gray-200 py-2 text-xs text-gray-500 shadow-sm">
                  Next
                </button>
                <p className="mt-4 text-[8px] font-medium leading-4 text-gray-500">
                  By clicking the Next button, you agree to creating a free
                  account, and to{" "}
                  <a href="#" className="font-bold text-blue-600">
                    terms of Service
                  </a>{" "}
                  and{" "}
                  <a href="#" className="font-bold text-blue-600">
                    Privacy Policy
                  </a>
                  .
                </p>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
