import type { NextPage } from "next";
import Head from "next/head";
import { Activity } from "phosphor-react";

const Home: NextPage = () => {
  return (
    <div className="flex h-screen w-screen flex-col items-center justify-center bg-blue-600">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-6xl font-bold text-white">Hello world!</h1>
      <Activity size={250} color="#ffffff" weight="fill" />
    </div>
  );
};

export default Home;
